### ISSUE TITLE
Fails under Python 2.7.10 (OS X El Cap native) as pysftp not found

### ISSUE THREAD

**Issue by dataknut** [developius/network-monitor#1]
->

Traceback (most recent call last):
  File "monitor.py", line 6, in <module>
    import subprocess, time, datetime, csv, os, pysftp, sys, json
ImportError: No module named pysftp

Presumably I only need psyftp if I want to upload the data (which I don't)

**Comment by developius** [comment]
You don't want this repo, you want developius/ping-log

**Comment by developius** [comment]
You don't want this repo for what you want to do, you need github.com/developius/ping-log

**Comment by developius** [comment]
You don't want this repo for what you want to do, you want http://github.com/developius/ping-log

**Comment by dataknut** [comment]
Traceback (most recent call last):
  File "./fxapinger.py", line 12, in <module>
    subprocess.call("rm results/" + sys.argv[1] + ".csv", shell=True)
IndexError: list index out of range

?
